# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitr" do
  name "gitr"
  desc "gitr: git rapid - save time by opening git repos on web right from the command line"
  homepage "https://github.com/swarupdonepudi/gitr"
  version "1.0.20"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitr"

  on_macos do
    on_intel do
      url "https://github.com/swarupdonepudi/gitr/releases/download/v#{version}/gitr_#{version}_darwin_amd64.tar.gz"
      sha256 "48411c3e035334cacda3c221f36c94dc87f4780097457caacab1d568f9f469ca"
    end
    on_arm do
      url "https://github.com/swarupdonepudi/gitr/releases/download/v#{version}/gitr_#{version}_darwin_arm64.tar.gz"
      sha256 "66efc6568d673ecd14f41855737819736993bb479c41493f8c60faa700c24865"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/swarupdonepudi/gitr/releases/download/v#{version}/gitr_#{version}_linux_amd64.tar.gz"
      sha256 "650de3617c662d7f017bea5cb8b74f163b2b56498bcae87a79fe6709dd3aca59"
    end
    on_arm do
      url "https://github.com/swarupdonepudi/gitr/releases/download/v#{version}/gitr_#{version}_linux_arm64.tar.gz"
      sha256 "a9a69359f2cd9c025a39f11dcb55638c1c1f8d9f494910b1dccce88b66bd30c6"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitr"]
    end
  end

  caveats do
    "Installation Complete!"
    ""
    "gitr helps you open git repositories in your browser instantly."
    ""
    "Quick Start"
    ""
    "1. Navigate to any git repository:"
    "   cd ~/your-project"
    ""
    "2. Open the repo in your browser:"
    "   gitr"
    ""
    "3. Open a specific page:"
    "   gitr pulls     # Pull requests"
    "   gitr issues    # Issues"
    "   gitr actions   # GitHub Actions"
    ""
    "4. Clone any repo with a short URL:"
    "   gitr clone gh/owner/repo"
    ""
    "For more commands, run:"
    "   gitr --help"
    ""
    "Documentation: https://gitr.dev"
  end

  # No zap stanza required
end
