# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitr" do
  name "gitr"
  desc "gitr: git rapid - save time by opening git repos on web right from the command line"
  homepage "https://github.com/swarupdonepudi/gitr"
  version "1.0.16"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitr"

  on_macos do
    on_intel do
      url "https://github.com/swarupdonepudi/gitr/releases/download/v#{version}/gitr_#{version}_darwin_amd64.tar.gz"
      sha256 "f49776b58358b8cc764e4064344ce017ea8a689a50e3577fff0d74de292eeb10"
    end
    on_arm do
      url "https://github.com/swarupdonepudi/gitr/releases/download/v#{version}/gitr_#{version}_darwin_arm64.tar.gz"
      sha256 "4574ba6af9ba3859c0f35763af3d86c99d0e2279786b169d16516dead24bb026"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/swarupdonepudi/gitr/releases/download/v#{version}/gitr_#{version}_linux_amd64.tar.gz"
      sha256 "c9e528bc0d0560cf751331c2091394fb26cc3fa03c3f398c146407928c0af64e"
    end
    on_arm do
      url "https://github.com/swarupdonepudi/gitr/releases/download/v#{version}/gitr_#{version}_linux_arm64.tar.gz"
      sha256 "d18220a53b2c226ee095fa5f6c28857c99d684f37b0e77a7f1c5a694bd534d92"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitr"]
    end
  end

  caveats do
    "Installation Complete!"
    ""
    "gitr helps you open git repositories in your browser instantly."
    ""
    "Quick Start"
    ""
    "1. Navigate to any git repository:"
    "   cd ~/your-project"
    ""
    "2. Open the repo in your browser:"
    "   gitr"
    ""
    "3. Open a specific page:"
    "   gitr pulls     # Pull requests"
    "   gitr issues    # Issues"
    "   gitr actions   # GitHub Actions"
    ""
    "4. Clone any repo with a short URL:"
    "   gitr clone gh/owner/repo"
    ""
    "For more commands, run:"
    "   gitr --help"
    ""
    "Documentation: https://gitr.dev"
  end

  # No zap stanza required
end
