# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitr" do
  name "gitr"
  desc "gitr: git rapid - save time by opening git repos on web right from the command line"
  homepage "https://github.com/swarupdonepudi/gitr"
  version "1.0.17"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitr"

  on_macos do
    on_intel do
      url "https://github.com/swarupdonepudi/gitr/releases/download/v#{version}/gitr_#{version}_darwin_amd64.tar.gz"
      sha256 "43f32a0f2e3b754e506ec1648dd1880917af65a5169c4ea46855b1c97daaa21c"
    end
    on_arm do
      url "https://github.com/swarupdonepudi/gitr/releases/download/v#{version}/gitr_#{version}_darwin_arm64.tar.gz"
      sha256 "da3d73943d2c0f63940eba65119c6973af94755668ccded1f97eadb05cba6f79"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/swarupdonepudi/gitr/releases/download/v#{version}/gitr_#{version}_linux_amd64.tar.gz"
      sha256 "4061bc1e31feab55acc1c48d6bfebedc6b6b146f29b2721db8ea06254f36812e"
    end
    on_arm do
      url "https://github.com/swarupdonepudi/gitr/releases/download/v#{version}/gitr_#{version}_linux_arm64.tar.gz"
      sha256 "e750f008c60189ecd4f4a2c052a9d8ba2a7c8c9349102633a5fdff9667948102"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitr"]
    end
  end

  caveats do
    "Installation Complete!"
    ""
    "gitr helps you open git repositories in your browser instantly."
    ""
    "Quick Start"
    ""
    "1. Navigate to any git repository:"
    "   cd ~/your-project"
    ""
    "2. Open the repo in your browser:"
    "   gitr"
    ""
    "3. Open a specific page:"
    "   gitr pulls     # Pull requests"
    "   gitr issues    # Issues"
    "   gitr actions   # GitHub Actions"
    ""
    "4. Clone any repo with a short URL:"
    "   gitr clone gh/owner/repo"
    ""
    "For more commands, run:"
    "   gitr --help"
    ""
    "Documentation: https://gitr.dev"
  end

  # No zap stanza required
end
