# This file was generated by GoReleaser. DO NOT EDIT.
cask "karayaml" do
  name "karayaml"
  desc "karayaml: YAML-powered shortcut launcher for Karabiner-Elements on macOS"
  homepage "https://karayaml.dev"
  version "0.0.15"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "karayaml"

  on_macos do
    on_intel do
      url "https://github.com/swarupdonepudi/karayaml/releases/download/v#{version}/karayaml_#{version}_darwin_amd64.tar.gz"
      sha256 "612e3ce41788c23320af94494eacb59febad22bab1318bc5697548f6b5358c74"
    end
    on_arm do
      url "https://github.com/swarupdonepudi/karayaml/releases/download/v#{version}/karayaml_#{version}_darwin_arm64.tar.gz"
      sha256 "2a1a065100701cc683db52c38633efae5d739707f1eb9126dcc95ca7de6b8e0f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/swarupdonepudi/karayaml/releases/download/v#{version}/karayaml_#{version}_linux_amd64.tar.gz"
      sha256 "9f5b1c88c2af381f43c78fbcfd23887796735219e4ecad3fe3e1307e2e59ea95"
    end
    on_arm do
      url "https://github.com/swarupdonepudi/karayaml/releases/download/v#{version}/karayaml_#{version}_linux_arm64.tar.gz"
      sha256 "18a4783a9d00672d294c55be2336a0a6e0c109cc5148981cdc1bdd466be51003"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/karayaml"]
    end
  end

  caveats do
    "Installation Complete!"
    ""
    "karayaml lets you define Karabiner-Elements shortcuts in simple YAML."
    ""
    "Quick Start"
    ""
    "1. Create your shortcuts config:"
    "   mkdir -p ~/.config/karayaml"
    "   touch ~/.config/karayaml/shortcuts.yaml"
    ""
    "2. Define shortcuts in YAML (example):"
    "   # ~/.config/karayaml/shortcuts.yaml"
    "   shortcuts:"
    "     - from: caps_lock"
    "       to: escape"
    ""
    "3. Generate and apply to Karabiner:"
    "   karayaml apply"
    ""
    "For more commands, run:"
    "   karayaml --help"
    ""
    "Documentation: https://karayaml.dev"
  end

  # No zap stanza required
end
