# This file was generated by GoReleaser. DO NOT EDIT.
cask "karayaml" do
  name "karayaml"
  desc "karayaml: YAML-powered shortcut launcher for Karabiner-Elements on macOS"
  homepage "https://karayaml.dev"
  version "0.0.18"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "karayaml"

  on_macos do
    on_intel do
      url "https://github.com/swarupdonepudi/karayaml/releases/download/v#{version}/karayaml_#{version}_darwin_amd64.tar.gz"
      sha256 "7506c79204582f532c9699e99ddcf52c45c5656349cbc855d932a5cbf483c8e4"
    end
    on_arm do
      url "https://github.com/swarupdonepudi/karayaml/releases/download/v#{version}/karayaml_#{version}_darwin_arm64.tar.gz"
      sha256 "f93fbb6f007ac9649b65ec94f136cc72b735dde78f22972a7e8d1828519b1458"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/swarupdonepudi/karayaml/releases/download/v#{version}/karayaml_#{version}_linux_amd64.tar.gz"
      sha256 "88c25aea047246e46895b0fa127b0b6a511144474ae72d199508b2e7d27a1ce1"
    end
    on_arm do
      url "https://github.com/swarupdonepudi/karayaml/releases/download/v#{version}/karayaml_#{version}_linux_arm64.tar.gz"
      sha256 "e4f5ec736b0d8af1b8004ff7fc20c3bc566b95350a606e220953d2a59c5aea3e"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/karayaml"]
    end
  end

  caveats do
    "Installation Complete!"
    ""
    "karayaml lets you define Karabiner-Elements shortcuts in simple YAML."
    ""
    "Quick Start"
    ""
    "1. Create your shortcuts config:"
    "   mkdir -p ~/.config/karayaml"
    "   touch ~/.config/karayaml/shortcuts.yaml"
    ""
    "2. Define shortcuts in YAML (example):"
    "   # ~/.config/karayaml/shortcuts.yaml"
    "   shortcuts:"
    "     - from: caps_lock"
    "       to: escape"
    ""
    "3. Generate and apply to Karabiner:"
    "   karayaml apply"
    ""
    "For more commands, run:"
    "   karayaml --help"
    ""
    "Documentation: https://karayaml.dev"
  end

  # No zap stanza required
end
