# This file was generated by GoReleaser. DO NOT EDIT.
cask "karayaml" do
  name "karayaml"
  desc "karayaml: YAML-powered shortcut launcher for Karabiner-Elements on macOS"
  homepage "https://karayaml.dev"
  version "0.0.19"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "karayaml"

  on_macos do
    on_intel do
      url "https://github.com/swarupdonepudi/karayaml/releases/download/v#{version}/karayaml_#{version}_darwin_amd64.tar.gz"
      sha256 "420799571777518de3be5e6d08ae499e732402a057b77ffe18896e2517a57fe7"
    end
    on_arm do
      url "https://github.com/swarupdonepudi/karayaml/releases/download/v#{version}/karayaml_#{version}_darwin_arm64.tar.gz"
      sha256 "e80f5635babb0118b4971e7330fed2958dd461a968cfc715db50169e5a80708f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/swarupdonepudi/karayaml/releases/download/v#{version}/karayaml_#{version}_linux_amd64.tar.gz"
      sha256 "1e97cd864ffb51febf9d79cfeccfed653b7f269078d7214b5de5a4f6a1a28d63"
    end
    on_arm do
      url "https://github.com/swarupdonepudi/karayaml/releases/download/v#{version}/karayaml_#{version}_linux_arm64.tar.gz"
      sha256 "63027d372a240d3a4a19daf07dbaa00adcd0ea2e3477a34fe69d88fe9f625367"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/karayaml"]
    end
  end

  caveats do
    "Installation Complete!"
    ""
    "karayaml lets you define Karabiner-Elements shortcuts in simple YAML."
    ""
    "Quick Start"
    ""
    "1. Create your shortcuts config:"
    "   mkdir -p ~/.config/karayaml"
    "   touch ~/.config/karayaml/shortcuts.yaml"
    ""
    "2. Define shortcuts in YAML (example):"
    "   # ~/.config/karayaml/shortcuts.yaml"
    "   shortcuts:"
    "     - from: caps_lock"
    "       to: escape"
    ""
    "3. Generate and apply to Karabiner:"
    "   karayaml apply"
    ""
    "For more commands, run:"
    "   karayaml --help"
    ""
    "Documentation: https://karayaml.dev"
  end

  # No zap stanza required
end
