# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitr < Formula
  desc "gitr: git rapid - save time by opening git repos on web right from the command line"
  homepage "https://github.com/swarupdonepudi/gitr"
  version "1.0.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/swarupdonepudi/gitr/releases/download/v1.0.9/gitr-darwin-amd64"
      sha256 "620218d919fe7536d12ab9ce529452619953cf09659bc72968758b716a19d4b7"

      def install
        bin.install "gitr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/swarupdonepudi/gitr/releases/download/v1.0.9/gitr-darwin-arm64"
      sha256 "77ba03b7fc7fc59ac6bf2b9eb30ee1e8758a189e80e5f01bf79d450c97cf4034"

      def install
        bin.install "gitr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/swarupdonepudi/gitr/releases/download/v1.0.9/gitr-linux-amd64"
      sha256 "a4b826616c1fe40b80e1f079355e9ffdddc4d8f06cd525533d46020d5f999022"
      def install
        bin.install "gitr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/swarupdonepudi/gitr/releases/download/v1.0.9/gitr-linux-arm64"
      sha256 "0b56880cf4af266ce5da52e0c5ff7e38beace49375bbfa2c1f44981480dbf5a7"
      def install
        bin.install "gitr"
      end
    end
  end

  def caveats
    <<~EOS
      Installation Complete!

      gitr helps you open git repositories in your browser instantly.

      Quick Start

      1. Navigate to any git repository:
         cd ~/your-project

      2. Open the repo in your browser:
         gitr

      3. Open a specific page:
         gitr pulls     # Pull requests
         gitr issues    # Issues
         gitr actions   # GitHub Actions

      4. Clone any repo with a short URL:
         gitr clone gh/owner/repo

      For more commands, run:
         gitr --help

      Documentation: https://gitr.dev
    EOS
  end
end
