# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitr < Formula
  desc "gitr: git rapid - save time by opening git repos on web right from the command line"
  homepage "https://github.com/swarupdonepudi/gitr"
  version "1.0.11"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/swarupdonepudi/gitr/releases/download/v1.0.11/gitr_1.0.11_darwin_amd64.tar.gz"
      sha256 "4b73a41969d5c3d014081260b56d9191966bfb01cd8d4a6381154b5f03fe452f"

      def install
        bin.install "gitr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/swarupdonepudi/gitr/releases/download/v1.0.11/gitr_1.0.11_darwin_arm64.tar.gz"
      sha256 "551b3cef696f19b9ea1e3dd87b711acd00ff30a80d6c8f2bd3070312609927a5"

      def install
        bin.install "gitr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/swarupdonepudi/gitr/releases/download/v1.0.11/gitr_1.0.11_linux_amd64.tar.gz"
      sha256 "c99d30742ffc5d27ea70f141ceac434051a253c8fb73f8a5abec5e9b32f094a9"
      def install
        bin.install "gitr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/swarupdonepudi/gitr/releases/download/v1.0.11/gitr_1.0.11_linux_arm64.tar.gz"
      sha256 "001c19a5afe864774651d8157a0add201956111bcf7277d204648f628f367621"
      def install
        bin.install "gitr"
      end
    end
  end

  def caveats
    <<~EOS
      Installation Complete!

      gitr helps you open git repositories in your browser instantly.

      Quick Start

      1. Navigate to any git repository:
         cd ~/your-project

      2. Open the repo in your browser:
         gitr

      3. Open a specific page:
         gitr pulls     # Pull requests
         gitr issues    # Issues
         gitr actions   # GitHub Actions

      4. Clone any repo with a short URL:
         gitr clone gh/owner/repo

      For more commands, run:
         gitr --help

      Documentation: https://gitr.dev
    EOS
  end
end
